app/be_the_hero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('hero/', include('hero.urls', namespace='hero')),
    path('home/', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('comment/', include('comment.urls')),

]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    #path('', views.index, name='home'),
    path('', views.PostListView.as_view(), name='home'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post'),
    path('new/', views.post_new, name='post_new'),
]

app/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation

from comment.models import Comment

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{0}'.format(self.name)

    def get_absolute_url(self):
        return reverse('category_detail', args=[str(self.id)])

class Post(models.Model):
    title= models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    text_body = models.TextField()
    comments = GenericRelation(Comment)

    def __str__(self):
        return '{0}'.format(self.title)

    def get_absolute_url(self):
        return reverse('blog:post', args=[str(self.id)])

            
    class Meta:
        ordering = ['-created']

app/blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'category','text_body')

app/blog/views.py
import datetime
from datetime import date, timedelta
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import generic 
from blog.models import Post, Category

from .forms import PostForm

def index(request):

    try:
        category = Category.objects.all()
        post = Post.objects.all()
    except:
        return render(request, 'blog/info_missing.html')
    else:
        context = {
            'categories': category,
            'posts': post,

        }

    return render(request, 'blog/index.html', context)


def post_new(request):
     if request.method == "POST":
         form = PostForm(request.POST)
         if form.is_valid():
             post = form.save(commit=False)
             post.author = request.user
             post.published_date =  datetime.datetime.now()
             post.save()
             return redirect('blog:post', pk=post.pk)
     else:
         form = PostForm()
     return render(request, 'blog/post_edit.html', {'form': form})


class PostListView(generic.ListView):
    context_object_name = 'post_list'
    template_name = 'blog/post_list.html'
    paginate_by = '4'

    def get_queryset(self):
        startdate = date.today()
        enddate = startdate + timedelta(days=6)
        posts = Post.objects.filter(created__range=[startdate, enddate])

        return posts
    
    def get_context_data(self, **kwargs):
        context=super(PostListView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context
    

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'



class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'blog/category_detail.html'

app/templates/blog/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : Escalate   
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20111121

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Escalate by TEMPLATED</title>
{% load static %}
<link href="{% static 'style.css' %}" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<div id="wrapper">

	<div id="menu">
		<ul>
			<li><a href="http://localhost:8000/home/">Homepage</a></li>
			<li><a href="{% url 'login' %}">Apps</a></li>
			<li class="current_page_item"><a href="#">Blog</a></li>
			<li><a href="#">About</a></li>
			<li><a href="#">Links</a></li>
		</ul>
	</div>

	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1><a href="#">Django Blog</a></h1>
				<p>Powered by <a href="#" rel="nofollow">Django</a></p>
			</div>
		</div>
	</div>

	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
						
					<div class="post">


						{% block content_post %}

						{% endblock %}

						{% block pagination %}
						{% if is_paginated %}
							<div class="pagination">
								<span class="page-links">
									{% if page_obj.has_previous %}
										<a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
									{% endif %}
									<span class="page-current">
										Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
									</span>
									{% if page_obj.has_next %}
										<a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
									{% endif %}
								</span>
							</div>
						{% endif %}
					{% endblock %}
					</div>
				
					<div style="clear: both;">&nbsp;</div>
				</div>
				<!-- end #content -->
				<div id="sidebar">
					<ul>
						{% if user.is_authenticated %}
							<a href="{% url 'blog:post_new' %}" class="top-menu">
								<img src="/mediafiles/plus.svg" alt="New Post" width="50" height="50">
							</a>
							<li>User: {{ user.get_username }}</li>
							<li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
						{% else %}
							<a href="{% url 'login'%}?next={{request.path}}"><p><strong>Login to create new posts...</strong></p></a>
						 {% endif %} 
						<li>
							<h2>Vídeos</h2>
							<ul>
								<li><a href="#">AutoCad</a></li>
								<li><a href="#">Projetos</a></li>
							</ul>
						</li>
						<li>
							<h2>Links Úteis</h2>
							<ul>
								<li><a href="#">Aliquam libero</a></li>
								<li><a href="#">Consectetuer adipiscing elit</a></li>
								<li><a href="#">Metus aliquam pellentesque</a></li>
							</ul>
						</li>
					</ul>
				</div>
				<!-- end #sidebar -->
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page --> 
</div>
<div id="footer">
</div>
<!-- end #footer -->
</body>
</html>

app/templates/blog/info_missing.html
{% extends "base.html" %}

{% block content %}

    <h2>Info Missing</h2>

    <p> Look like you foggot to add your informations</p>
    <p> Go to the Admin's Page to set some infos about your Bio, Jobs, Tools and Languages </p>

{% endblock %}

app/templates/blog/post_detail.html
{% extends 'blog/index.html' %}

{% block content_post %}
    
    <h2 class="title"><a href="#">{{ post.title }}</a></h2>
    <p class="meta">Postado em {{ post.post_date }}
        &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">{{ post.category }}</a></p>
    <div class="entry"> <a href="#" class="image image-full"><img src="images/pics01.jpg" alt="" /></a>
        <p> {{ post.text_body }}... </p>
    </div>
    <div>
        <a href="{% url 'blog:home' %}"><button type="button" class="button">Voltar</button></a>
    </div>

{% endblock %}

app/templates/blog/post_edit.html
{% extends 'blog/index.html' %}

{% block content_post %}
    
    {% if user.is_authenticated %}
    <a href="{% url 'blog:home' %}">
        <img src="/mediafiles/back.svg" width="50" height="50">
    </a>
    <h2>New post</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    {% else %}
    <h2>Access Denied!</h2>
    <p>You must to login to post.</p>
    {% endif %}
{% endblock %}

app/templates/blog/post_list.html
{% extends 'blog/index.html' %}

{% block content_post %}

    {% for post in post_list %}

    <div class="post-container">
        <h2 class="title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="meta">Postado em {{ post.post_date }}
            &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a href="#" class="permalink">{{ post.category }}</a></p>
        <div class="entry"> <a href="#" class="image image-full"><img src="images/pics01.jpg" alt="" /></a>
            <p> {{ post.text_body|slice:300 }}... </p>
        </div>
        <div class="post-button">
            <button type="button" class="button">Leia Mais</button>
        </div>

        <hr  WIDTH=85% ALIGN=left NOSHADE>
    </div>

    {% endfor %}
{% endblock %}