app/be_the_hero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('hero/', include('hero.urls', namespace='hero')),
    path('home/', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('comment/', include('comment.urls')),

]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    #path('', views.index, name='home'),
    path('', views.PostListView.as_view(), name='home'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post'),
    path('new/', views.post_new, name='post_new'),
]

app/hero/urls.py
from django.urls import path 

from . import views

app_name = 'hero'
urlpatterns = [
    path('', views.index, name='index'),

    path('incidents/', views.IncidentListView.as_view(), name='incidents'), 

    path('incident/<int:pk>', views.IncidentDetailView.as_view(), name='incident-detail'),

    path('incident/create', views.IncidentCreateView.as_view(), name='incident-create'),

    path('incident/<int:pk>/update', views.IncidentUpdateView.as_view(), name='incident-update'),

    path('incident/<int:pk>/delete', views.IncidentDeleteView.as_view(), name='incident-delete'),

    path('ngos/', views.NgoListView.as_view(), name='ngos'),

    path('ngo/<int:pk>', views.NgoDetailView.as_view(), name='ngo-detail'),

    path('ngo/create/', views.NgoCreate.as_view(), name='ngo-create'),

    path('ngo/<int:pk>/update', views.NgoUpdate.as_view(), name='ngo-update'),

    path('ngo/<int:pk>/delete', views.NgoDelete.as_view(), name='ngo-delete'),

    path('upload/', views.image_upload, name='upload'),

#    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
#
#    path('borrowedbooks/', views.LoanedBooksListView.as_view(), name='borrowed-books'),
#
#    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),

]

app/hero/models.py
import uuid
from datetime import date 

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


#class Genre(models.Model):
#    """ 
#    Model representing a book genre
#    """
#    name = models.CharField(
#        max_length=200, 
#        help_text='Enter a book genre (e.g. Science Fiction)'
#        )
#
#    def __str__(self):
#        """
#        String for representing the Model object.
#        """
#        return self.name
    

#class Language(models.Model):
#    """
#    Model representing a Language (e.g. English, French, Japanese, etc.)
#    """
#    name = models.CharField(max_length=200, 
#                            help_text="Enter the book's natural language (e.g. English, French, Japanese, etc)")
#
#    def __str__(self):
#        """String for representing the Model object (in Admin site etc.)"""
#        return self.name 


class Incident(models.Model):
    """
    Model representing a Incidents.
    """
    title = models.CharField(max_length=200)
    ngo = models.ForeignKey('Ngo', on_delete=models.CASCADE)
    description = models.TextField(max_length=1000, help_text='Enter a brief description of the NGO')
    value = models.IntegerField()

    class Meta:
        ordering = ['title', 'ngo']

#    def display_genre(self):
#        """
#        Create a string for the Genre. This is required to display genre in Admin.
#        """
#        return ', '.join([ngo.name for ngo in self.ngo.all()[:3]])
#
#    display_ngo.short_description = 'Genre'    

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book
        """
        return reverse('hero:incident-detail', args=[str(self.id)])
        
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title
        

#class BookInstance(models.Model):
#    """
#    Model representing a specific copy of a book 
#    (i.e that can be borrowed from the library).
#    """
#    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
#                          help_text="Unique ID for this particular book across whole library")
#    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
#    imprint = models.CharField(max_length=200)
#    due_back = models.DateField(null=True, blank=True)
#    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
#
#
#    @property
#    def is_overdue(self):
#        if self.due_back and date.today() > self.due_back:
#            return True
#        return False
#
#    LOAN_STATUS = (
#        ('d', 'Maintenance'),
#        ('o', 'On loan'),
#        ('a', 'Available'),
#        ('r', 'Reserved'),
#    )
#
#    status = models.CharField(
#        max_length=1,
#        choices=LOAN_STATUS,
#        blank=True,
#        default='d',
#        help_text='Book availability')
#
#    class Meta:
#        ordering = ['due_back']
#        permissions = (("can_mark_returned", "Set book as returned"),)
#
#    def __str__(self):
#        """
#        String for representing the Model object.
#        """
#        return '{0} ({1})'.format(self.id, self.book.title)

class Ngo(models.Model):
    """
    Model representing an author.
    """
    name = models.CharField(max_length=100)
    email = models.EmailField()
    description = models.TextField()
    whatsapp = models.IntegerField()
    city = models.CharField(max_length=100)
    ur = models.CharField(max_length=2)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        """
        Return the url to access a particular ngo instance.
        """
        return reverse('hero:ngo-detail', args=[str(self.id)])
            
    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}'.format(self.name)

app/hero/forms.py
#import datetime
#
#from django import forms 
#from django.core.exceptions import ValidationError
#from django.utils.translation import ugettext_lazy as _ 
#
#
#
#class RenewBookForm(forms.Form):
#    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
#
#    def clean_renewal_date(self):
#        data = self.cleaned_data['renewal_date']
#
#        # Check if a date is not in the past.
#        if data < datetime.date.today():
#            raise ValidationError(_('Invalid date - renewal in past'))
#
#        # Check if a date is in the allowed range (+4 weeks from today).
#        if data > datetime.date.today() + datetime.timedelta(weeks=4):
#            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
#
#        # Remember to always return the cleaned data.
#        return data

app/hero/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
#require login to function based view
from django.contrib.auth.decorators import login_required, permission_required
#require login to class based view
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.files.storage import FileSystemStorage

from hero.models import Incident, Ngo
#from hero.forms import RenewBookForm


def index(request):
    """
    View function for home page of site.
    """

    # Generate counts of some of the main objects 
    num_incidents = Incident.objects.all().count()
    num_ngos = Ngo.objects.all().count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    
    context = {
        'num_incidents': num_incidents,
        'num_ngos': num_ngos,
    }

    return render(request, 'hero/index.html', context=context)


def image_upload(request):
    if request.method == "POST" and request.FILES["image_file"]:
        image_file = request.FILES["image_file"]
        fs = FileSystemStorage()
        filename = fs.save(image_file.name, image_file)
        image_url = fs.url(filename)
        print(image_url)
        return render(request, "hero/upload.html", {
            "image_url": image_url
        })
    return render(request, "hero/upload.html")

#@login_required
#@permission_required('hero.can_mark_returned', raise_exception=True)
#def renew_book_librarian(request, pk):
#    book_instance = get_object_or_404(BookInstance, pk=pk)
#
#    # If this is a POST request then process the Form data
#    if request.method == 'POST':
#
#        # Create a form instance and populate it with data from the request (binding):
#        form = RenewBookForm(request.POST)
#
#        # Check if the form is valid:
#        if form.is_valid():
#            # Process the data in form.cleaned_data as required (here we just write it to the model due_back field).
#            book_instance.due_back = form.cleaned_data['renewal_date']
#            book_instance.save()
#
#            # Redirect to a new URL:
#            return HttpResponseRedirect(reverse('borrowed-books'))
#    # If this is a GET (or any other method) create the default form
#    else: 
#        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
#        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
#
#    context = {
#        'form': form,
#        'book_instance': book_instance,
#    }
#
#    return render(request, 'hero/book_renew_librarian.html', context)


class IncidentListView(generic.ListView):
    model = Incident
    context_object_name = 'incident_list'
    queryset = Incident.objects.all()
    template_name = "hero/incident_list.html"
    paginate_by = 10


class IncidentDetailView(generic.DetailView):
    model = Incident
    template_name = "hero/incident_detail.html"


class NgoListView(generic.ListView):
    model = Ngo
    context_object_name = 'ngo_list'
    queryset = Ngo.objects.all()
    template_name = "hero/ngo_list.html"
    paginate_by = 10


class NgoDetailView(generic.DetailView):
    """
    Generic class-based detail view for an author.
    """
    model = Ngo
    template_name = "hero/ngo_detail.html"


#class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
#    """
#    Generic class-based view listing books on loan to current user
#    """
#    model = BookInstance
#    template_name = "hero/bookinstance_list_borrowed_user.html"
#    paginate_by = 10
#
#    def get_queryset(self):
#        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    

#class LoanedBooksListView(PermissionRequiredMixin, generic.ListView):
#    model = BookInstance
#    permission_required = 'hero.can_mark_returned'
#    template_name = "hero/bookinstance_list_borrowed.html"
#
#    def get_queryset(self):
#        return BookInstance.objects.filter(status__exact='o').order_by('due_back')
#
#"""
#For this kind of Class Based View the Django expects a Template name with a certain pattern
#Ex: for a BookCreateView it expects a template as 'book_form.html' or 'MODEL_form.html
#For a BookDeleteView it expects a template as 'book_confirm_delete.html' or 'MODEL_confirm_delete.html'
#It dispenses you set a 'template_name' in this view case. If you don't follow the pattern you shoud to point a 'template_name'
#"""


class NgoCreate(CreateView):
    model = Ngo
    fields = ['name', 'email', 'description', 'whatsapp', 'city', 'ur']

class NgoUpdate(UpdateView):
    model = Ngo
    fields = ['name', 'email', 'description', 'whatsapp', 'city', 'ur']  # '__all__'  Not recomended (Potential security issue if more fields added)

class NgoDelete(PermissionRequiredMixin ,DeleteView):
    model = Ngo
    success_url = reverse_lazy('ngos')

class IncidentCreateView(CreateView):
    model = Incident
    fields = ['title', 'ngo', 'description', 'value']

class IncidentUpdateView(UpdateView):
    model = Incident
    fields = '__all__' 

class IncidentDeleteView(DeleteView):
    model = Incident
    success_url = reverse_lazy('incidents')

app/templates/hero/incident_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    
    <h1>Delete Incident</h1>
    
    <p>Are you sure you want to delete the Incident: {{ incident }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete!">
    </form>

{% endblock %}

app/templates/hero/incident_detail.html
{% extends "base.html" %}

{% block content %}

    <h1> Title: {{ incident.title }}</h1>
    <p><strong>NGO:</strong><a href=""> {{ incident.ngo }} </a></p>
    <p><strong>Description:</strong> {{ incident.description }} </p>
    <p><strong>Value:</strong> {{ incident.valu }} </p>

{% endblock %}

app/templates/hero/incident_form.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

app/templates/hero/incident_list.html
{% extends "base.html" %}

{% block static %}
{% load static %}
<linK rel="stylesheet" href="{% static 'css/incident_list.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">    <link red="stylesheet" href="{% static 'js/jquery-3.3.1.slim.min.js' %}">

{% endblock %}

{% block content %}

<div class="container incident-container">    
    <div class="row">
        <h2 class="col-md-5 incident-list">Incident List</h2>     
        <a class="button col-md-5" href="{% url 'hero:incident-create' %}">New Incident</a></button>
    </div>


    {% if incident_list %}

        <ul class="row">
            {% for incident in incident_list %}        
            
                <li class="col-md-5">
                    <strong>INCIDENT:</strong>
                    <a href="{{ incident.get_absolute_url }}">{{ incident.title }}</a>
                    <p>({{ incident.ngo }})</p> 
                    <srong>DESCRIPTION</srong>
                    <p>{{ incident.description }}</p>

                    <strong>VALUE:</strong>
                    <p>{{ incident.value }}</p>

                    <td><a href="url:delete_view" part.id><i class="fa fa-trash"></i></a></td>          
                </li>    

            {% endfor %}
        </ul>
       
    {% else %}
        <p>There are no incidets in the library.</p>
    {% endif %}
</div>
{% endblock %}

app/templates/hero/index.html
{% extends 'base.html' %}

{% block title %}<title>Local Library</title>{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-10 about">
        {% if user.is_authenticated %}
        <h2>Welcome to <strong>Hero</strong></h2>

        <p class="about-txt">                
            A Django-based adaptation of the <strong>Be The Hero </strong> application, taught at the 11th edition of the week OmniStack
            Developed by Rocketseat. Originally done entirely with the JavaScript libraries React and React Native in conjunction with Node.js
            and an SQLite database.
            At this version I use a Python Stack, with the Django framework as a backend together with Gunicorn and Nginx to serve
            HTML templates and statistical files, as well as a PostgreSQL database.

            Be The Hero (django version)
            Application to connect NGOs and other institutions to people who are available to help.
            Powered By Django, developed by <em>Bruno Terres</em>!
        </p>
        
        <p>
            Hello <strong>{{ user.get_username }}</strong> now you can create NGOs and Incidents, try it!
        </p>

        <h4>COUNTER</h4>
        <p>NGOs: {{ num_ngos }}</p>
        <p>Incidents: {{ num_incidents }}</p>

        <p>
            All NGOs registered here are just ficticial examples to show you the <strong>Hero</strong> aplication.
            Email sender is deactivated to avoid spam.
        </p>

        {% else %}

        <h2>Welcome to <strong>Hero</strong></h2>

        <p>                
            A Django-based adaptation of the <strong>Be The Hero </strong> application, taught at the 11th edition of the week OmniStack
            Developed by Rocketseat. Originally done entirely with the JavaScript libraries React and React Native in conjunction with Node.js
            and an SQLite database.
            At this version I use a Python Stack, with the Django framework as a backend together with Gunicorn and Nginx to serve
            HTML templates and statistical files, as well as a PostgreSQL database.

            Be The Hero (django version)
            Application to connect NGOs and other institutions to people who are available to help.
            Powered By Django, developed by <em>Bruno Terres</em>!
        </p>
       
        <p><strong><a href="{% url 'login' %}">Login</a>to Create NGOs and Incidents.</strong></p>

        <h4>COUNTER</h4>
        <p>NGOs: {{ num_ngos }}</p>
        <p>Incidents: {{ num_incidents }}</p>

        <p>
            All NGOs registered here are just ficticial examples to show you the <strong>Hero</strong> aplication.
            Email sender is deactivated to avoid spam.
        </p>

        {% endif %}
    </div>
     
</div>


<div class="return">
    <h3 >Or Return to :</h3>
    <div class="row">
        <a href="{% url 'home:home' %}" class="col-md-3 button return-btn">HomePage</a>
        <a href="{% url 'login' %}" class="col-md-3 button return-btn">Apps</a>
    </div>
</div>
{% endblock %}

app/templates/hero/ngo_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    
    <h1>Delete NGO</h1>

    <p>Are you sure you want to delete the NGO: {{ ngo }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>

{% endblock %}

app/templates/hero/ngo_detail.html
{% extends "base.html" %}

{% block content %}

    <h1>NGO: {{ ngo.name }}</h1>
    <p><strong>Email:</strong><a href=""> {{ ngo.email }} </a></p>
    <p><strong>Description:</strong> {{ ngo.description }} </p>
    <p><strong>Whatsapp:</strong> {{ ngo.whatsapp }} </p>
    <p><strong>City:</strong> {{ ngo.city }} </p>
    <p><strong>UR:</strong> {{ ngo.ur }} </p>

    
    <div style="margin-left: 20px; margin-top:20px;">
        <h4>Incidents</h4>

        <d1>
        {% for incident in ngo.incident_set.all %}
            <dt><a href="{% url 'hero:incident-detail' incident.pk %}">{{ incident }}</a></dt>
            <dd>{{ Incident.description }}</dd>
        {% endfor %}
        </d1>
    </div>

{% endblock %}

app/templates/hero/ngo_form.html
{% extends "base.html" %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

app/templates/hero/ngo_list.html
{% extends "base.html" %}

{% block static %}
{% load static %}
<linK rel="stylesheet" href="{% static 'css/ngo_list.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">    <link red="stylesheet" href="{% static 'js/jquery-3.3.1.slim.min.js' %}">

{% endblock %}

{% block content %}

<div class="container ngo-container">  

    <div class="row">
        <h2 class="col-md-5 ngo-list">NGO's List</h2>     
        <a class="button col-md-5" href="{% url 'hero:ngo-create' %}">New Incident</a></button>
    </div>

    {% if ngo_list %}
        <ul>
            {% for ngo in ngo_list %}
            <li class=" ngo-card col-md-5">
                <strong>NGO:</strong>
                <a href="{{ ngo.get_absolute_url }}">{{ ngo.name }}</a>
                <strong>Description:</strong>
                <p>({{ ngo.description }})</p> 
                <srong>Location</srong>
                <p>{{ ngo.city }} - {{ ngo.ur }}</p>



                <td><a href="url:delete_view" part.id><i class="fa fa-trash"></i></a></td>          
            </li>        

            {% endfor %}
        </ul> 
    {% else %}
        <p>There are no NGO's to list.</p>
    {% endif %}
{% endblock %}





    {% if incident_list %}

        <ul class="row">
            {% for incident in incident_list %}        
            
                <li class="col-md-5">
                    <strong>INCIDENT:</strong>
                    <a href="{{ incident.get_absolute_url }}">{{ incident.title }}</a>
                    <p>({{ incident.ngo }})</p> 
                    <srong>DESCRIPTION</srong>
                    <p>{{ incident.description }}</p>

                    <strong>VALUE:</strong>
                    <p>{{ incident.value }}</p>

                    <td><a href="url:delete_view" part.id><i class="fa fa-trash"></i></a></td>          
                </li>    

            {% endfor %}
        </ul>
       
    {% else %}
        <p>There are no incidets in the library.</p>
    {% endif %}
</div>

app/templates/hero/ong_register.html
{% extends 'base.html' %}

{% block title %} Ong Registration {% endblock %}

{% block content %}
<div>
    <div>
        <h1 style='font-weight: bold;'>Cadastro</h1>     
        <p>Register, enter the platform and help people contact your NGO's cases.</p>
        <p><a href="">I don't have register</a></p>
    </div>
    
    <div>
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/hero/upload.html
{% block content %}

  <form action="{% url 'hero:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image_file">
    <input type="submit" value="submit" />
  </form>

  {% if image_url %}
    <p>File uploaded at: <a href="{{ image_url }}">{{ image_url }}</a></p>
  {% endif %}

{% endblock %}