app/be_the_hero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('hero/', include('hero.urls', namespace='hero')),
    path('home/', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('comment/', include('comment.urls')),

]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    #path('', views.index, name='home'),
    path('', views.PostListView.as_view(), name='home'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post'),
    path('new/', views.post_new, name='post_new'),
]

app/hero/urls.py
from django.urls import path 

from . import views

app_name = 'hero'
urlpatterns = [
    path('', views.index, name='index'),

    path('incidents/', views.IncidentListView.as_view(), name='incidents'), 

    path('incident/<int:pk>', views.IncidentDetailView.as_view(), name='incident-detail'),

    path('incident/create', views.IncidentCreateView.as_view(), name='incident-create'),

    path('incident/<int:pk>/update', views.IncidentUpdateView.as_view(), name='incident-update'),

    path('incident/<int:pk>/delete', views.IncidentDeleteView.as_view(), name='incident-delete'),

    path('ngos/', views.NgoListView.as_view(), name='ngos'),

    path('ngo/<int:pk>', views.NgoDetailView.as_view(), name='ngo-detail'),

    path('ngo/create/', views.NgoCreate.as_view(), name='ngo-create'),

    path('ngo/<int:pk>/update', views.NgoUpdate.as_view(), name='ngo-update'),

    path('ngo/<int:pk>/delete', views.NgoDelete.as_view(), name='ngo-delete'),

    path('upload/', views.image_upload, name='upload'),

#    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
#
#    path('borrowedbooks/', views.LoanedBooksListView.as_view(), name='borrowed-books'),
#
#    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),

]

app/home/urls.py
from django.urls import path

from . import views

app_name = 'hero'
urlpatterns = [
    path('', views.index, name='home'),
    path('bio/', views.BioView.as_view(), name='bio'),
    path('safe/', views.SafeView.as_view(), name='safe'),
    path('fast/', views.FastView.as_view(), name='fast'),
    path('responsive/', views.ResponsiveView.as_view(), name='responsive'),
    path('jobs/', views.JobListView.as_view(), name='jobs'),
    path('job/<int:pk>', views.JobDetailView.as_view(), name='job_detail'),
    #path('tools/', views.ToolListView.as_view(), name='tools'),
    #path('tool/<int:pk>', views.ToolDetailView.as_view(), name='tool_detail'),
    #path('languages/', views.LanguageListView.as_view(), name='languages'),
    #path('language/<int:pk>', views.LanguageDetailView.as_view(), name='language_detail'),
    path('contact/', views.ContactCreateView.as_view(), name='contact'),
    #path('upload', views.image_upload, name="upload"),
    path('tools/', views.tools, name='tools'), 
    path('languages/', views.languages, name='languages'),
]   

app/templates/base.html
<DOCTYPE html>

<html>
<head>
    {% block title %}<title>hero</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add addiitional CSS in static file -->
    
    {% load static %}
    <linK rel="stylesheet" href="{% static 'css/styles.css' %}">
    <linK rel="stylesheet" href="{% static 'css/global.css' %}">
    {% block static %}
    
    {% endblock %}

</head>
<body>

    <div id="menu" class="header">

            <a href="" class="logo">   
                <img src='/mediafiles/logo_2mLetLB.svg' alt="Be The Hero" width="100" height="50"/>
            </a>

        <div class="header-right">

            <ul>
                <li><a href="{% url 'hero:index' %}" class="header-link">About</a></li>
                <li><a href="{% url 'hero:ngos' %}" class="header-link">NGOs</a></li>
                <li><a href="{% url 'hero:incidents' %}" class="header-link">Incidents</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
            </ul>

        </div>
      
    </div> 

    <div class="container-fluid content-container">
        <div class="row">


                <div class="block-content">
                {% block content %}
                
                {% endblock %}
                </div>
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% endblock %}

        </div>
    </div>
</body>
</html>

app/templates/base2.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  {% block head-meta %}
    <meta charset="utf-8" http-equiv="Content-Type" content="text/html; charset=utf-8">
  {% endblock %}

  {% block title %}
    <title>Authentication</title>
  {% endblock %}

  {% load static %}
  {% block style %}
    <link href="{% static 'static/main.css'%}" rel="stylesheet" type="text/css" media="all">
  {% endblock %}
</head>
<body>
  <main>
    <h1 class='homebase'>base</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

app/templates/base_home.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : Hyacinth 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20131010
-->

<html>
<head>

    {% block head-meta %}
         <meta charset="utf-8">
         <!-- Add here the kaywords that describe the project -->
         <meta name="keywords" content="portfolio, web dev, django">
         <meta http-equiv="X-UA-Compatible" content="IE=edge">
         <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}
    
    {% block title %}
        <title>Home</title>
    {% endblock %}


    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">    {% load static %}
    <link rel="stylesheet" href="{% static 'css/pages.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}"> 
    {% block style %}

    {% endblock %}
</head> 
<body>

    {% block header %}

    <div id="header-wrapper">
        
        <div id="header" class="container mmenu">
            <div id="logo">
                <h1><a href="{% url 'home:home' %}">Bruno Terres</a></h1>
                <span>A Full Stack Web Developer</span>
            </div>
        
            <div id="menu">
                <ul>
                    <li><a href="{% url 'home:tools' %}" accesskey="2" title="">Tools</a></li>
                    <li><a href="#portfolio" accesskey="3" title="">Experience</a></li>
                    <li><a href="{% url 'home:contact' %}" accesskey="3" title="" class="contact-btn">Contact</a></li>
                    <li><a href="{% url 'home:bio' %}" accesskey="4" title="">About</a></li>
                </ul>

            </div>
            <ul class="actions arrow-down">
                <a href="#go-to" class="icon"><img class="img-responsive contact-img"src="/mediafiles/down-arrow.svg" width="50px" height="50px" alt="whats app link"></a>                
            </ul>
        </div>

        <div id="go-to"></div>

        <div id="three-column" class="container">

            <div>
                <h2 id="welcome-to">Welcome to my site</h2>
                <p class="welcome-txt">Building web applications with technologies that take seriously some of the main challenges of industry 4.0</p>
                <p></p>
            </div>

            <div id="tbox1">
                <div class="icon icon-wrench atribute-img">
                    <img src='/mediafiles/lighting.svg' alt="Fast" width="100" height="100"/>
                </div>
                <div class="title">
                    <h2>FAST</h2>
                </div>
            </div>
            <div id="tbox2">
                <div class="icon icon-wrench atribute-img">
                    <img src='/mediafiles/cloud-computing.svg' alt="Cloud Computing" width="100" height="100"/>
                </div>
                <div class="title">
                    <h2>CLOUD <br>BASED</h2>
                </div>
                <a href="#portfolio" class="button-exp button button-small" accesskey="3" title="">Experience</a>
            </div>

            <div id="tbox3">
                <div class="icon icon-wrench atribute-img">
                    <img src='/mediafiles/shield.svg' alt="Safe" width="100" height="100"/>
                </div>
                <div class="title">
                    <h2>SAFE</h2>
                </div>
            </div>

        </div>
    </div>

    {% endblock %}

    <div>
        <div id="wrapper3">
            <div id="portfolio" class="container">
    
                <div class="title">
                    <h1 id="experience"  class="byline">Experience</h1>
                </div>
    
                <div class="row ">
    
                    <div class="col column">
                      <div class="box">

                        <a href="http://localhost:8000/hero">
                            <img src='/mediafiles/logo_2mLetLB.svg' alt="Be The Hero" width="100" height="100"/>
                        </a>

                        <h3 class="job-title">Be The Hero</h3>
                        <p class="job-description">Application to connect NGOs and other institutions to people who are available to help.</p>
                        
                        {% if user.is_authenticated %}
                            <a href="http://localhost:8000/hero" class="button button-small">More</a>
                        {% else %}
                            <a href="http://localhost:8000/auth/login/" class="button button-small">More</a>
                        {% endif %}  
                                        
                        </div>
                    </div>

                    <div class="col column">
                        <div class="box">
  
                          <a href="http://localhost:8000/blog">
                              <img src='/mediafiles/blog.jpeg' alt="Blog" width="100" height="100"/>
                          </a>
  
                          <h3 class="job-title">Django Blog</h3>
                          <p class="job-description">A generic Django Blog Web App that receive Posts and Comments.</p>
                          
                          {% if user.is_authenticated %}
                            <a href="http://localhost:8000/blog" class="button button-small">More</a>
                          {% else %}
                             <a href="http://localhost:8000/auth/login/" class="button button-small">More</a>
                          {% endif %}
                          
                        </div>
                      </div>

                      <div class="col column">
                        <div class="box">
  
                          <a href="">
                              <img src='/mediafiles/safeplace.png' alt="Safe Place" width="100" height="100"/>
                          </a>
  
                          <h3 class="job-title">Safe place</h3>
                          <p class="job-description">A Web App developed to make shared environments safer in Covid-19 pandemic times.</p>
                          
                          {% if user.is_authenticated %}
                            <a href="" class="button button-small">More</a>
                          {% else %}
                            <a href="http://localhost:8000/auth/login/" class="button button-small">More</a>
                          {% endif %}  
                          
                        
                        </div>
                      </div>
                
                </div>
            </div>  
        </div>  
    </div>

    {% block footer %}

    <div class="wrapper4">
        <div id="footer" class="container">
            <div>
                <header class="title">
                    <h2>Get in touch</h2>
                    <span class="byline">Let's build something great together!</span> 
                </header>

			    <ul class="contact row">
				    <li class="col-md-3"><a href="#" class="icon icon-twitter"><img class="img-responsive contact-img"src="/mediafiles/github(1).svg" width="50px" height="50px" alt="linkedin link">
				    <li class="col-md-3" ><a href="#" class="icon icon-facebook"><img class="img-responsive contact-img"src="/mediafiles/gmail(1).svg" width="50px" height="50px" alt="github link"></a></li>
				    <li class="col-md-3"><a href="#" class="icon icon-dribbble"><img class="img-responsive contact-img"src="/mediafiles/linkedin(1).svg" width="50px" height="50px" alt="messager link"></a></li>
				    <li class="col-md-3"><a href="#" class="icon icon-tumblr"><img class="img-responsive contact-img"src="/mediafiles/whatsapp.svg" width="50px" height="50px" alt="whats app link"></a></li></a></li>
			    </ul>
		    </div>
	    </div>
    </div>

    <div id="copyright" class="container">
        <p>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></p>

    	<p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
    </div>

    {% endblock %}
</body>

</html> 

app/templates/base_pages.html
<html>
<head>

    {% block head-meta %}
         <meta charset="utf-8">
         <!-- Add here the kaywords that describe the project -->
         <meta name="keywords" content="portfolio, web dev, django">
         <meta http-equiv="X-UA-Compatible" content="IE=edge">
         <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}
    
    {% block title %}{% endblock %}

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/pages.css' %}">
    {% block style %}
    {% endblock %}

</head> 
<body>
        
    {% block header %}

        <div class="header">
          <div class="header-center">
            <a class="logo" href="{% url 'home:home' %}">Home</a>
            <a href="{% url 'home:tools' %}">Tools</a>
            <a href="{% url 'home:languages' %}">Languages</a>
            <a href="{% url 'home:bio' %}">About</a>
          </div>
        </div>

    {% endblock %}

    <div>
        {% block content %}{% endblock %}
    </div>

    {% block footer %}{% endblock %}
</body>
</html> 

app/templates/info_missing.html
{% extends "base_home.html" %}

{% block content %}

    <h2>Info Missing</h2>

    <p> Look like you foggot to add your informations</p>
    <p> Go to the Admin's Page to set some infos about your Bio, Jobs, Tools and Languages </p>

{% endblock %}